name: medial_match
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  get_it: ^7.3.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  faker: ^2.1.0
  http: ^0.13.5
  logger: ^1.3.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  vector_graphics: ^1.1.5
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

dev_dependencies:

  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  vector_graphics_compiler: ^1.1.5

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

  fonts:
  
    - family: MedialNow
      fonts:
        - asset: assets/fonts/now_bold.otf

    - family: MedialOne
      fonts:
        - asset: assets/fonts/fjalla_one.ttf

flutter_native_splash:
  color: "#b500ff"
  image: "docs/assets/icons/white_label.png"
  branding: "docs/assets/icons/white_proconda.png"
  branding_mode: bottom

flutter_launcher_icons:
  android: true
  image_path: "docs/assets/icons/white_logo.png"
  background_color: "#b500ff"
  adaptive_icon_foreground: "docs/assets/icons/white_logo_padding.png"
  adaptive_icon_background: "#b500ff"